version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: docker-php/Dockerfile
    volumes:
      - ./:/var/www/app
      #- ./docker-php/config/php.ini:/usr/local/etc/php/php.ini
    expose:
      - '9000'
    links:
      - "mysql-php:mysql"
  hhvm:
    build:
      context: .
      dockerfile: docker-hhvm/Dockerfile
    volumes:
      - ./:/var/www/app
    expose:
      - '9000'
    links:
      - "mysql-hhvm:mysql"
  nginx-php:
    build: ./nginx
    volumes:
      - ./:/var/www/app
      - ./nginx/config/php/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8081:80"
    links:
        - php
  nginx-hhvm:
    build: ./nginx
    volumes:
      - ./:/var/www/app
      - ./nginx/config/hhvm/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8082:80"
    links:
        - hhvm
  mysql-php: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: wordpress
    volumes:
      - ~/data-php:/var/lib/mysql
  mysql-hhvm: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: wordpress
    volumes:
      - ~/data-hhvm:/var/lib/mysql
